spring.application.name=bff
server.port=8080
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}
product.service.url=${PRODUCT_SERVICE_URL:http://localhost:8082}
inventory.service.url=${INVENTORY_SERVICE_URL:http://localhost:8083}
sales.service.url=${SALES_SERVICE_URL:http://localhost:8084}
notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8085}



# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
